/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group55.bd_lab;

import com.group55.bd_lab.views.Pizza_CargoPanel;
import javax.swing.JFrame;

/**
 *
 * @author anjab
 */
public class PizzeriaCargo extends javax.swing.JFrame {

    /**
     * Creates new form PizzeriaCargo
     */
    public PizzeriaCargo() {
        initComponents();
        setupJFrame();
    }
    
    private void setupJFrame() {
        this.pack();
        this.setTitle("Cargo - Pizzeria");
        this.setLocationRelativeTo(null); // Screen center
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_TamanhoPizza = new javax.swing.JButton();
        jButton_TamanhoBocadillo = new javax.swing.JButton();
        jButton_Articulo = new javax.swing.JButton();
        jButton_Ingrediente = new javax.swing.JButton();
        jButton_Venta = new javax.swing.JButton();
        jButton_Scooter = new javax.swing.JButton();
        jButton_TipoPedido = new javax.swing.JButton();
        jButton_Cliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton_Pizza = new javax.swing.JButton();
        jButton_Bocadillo = new javax.swing.JButton();
        jButton_ProductoEstrella = new javax.swing.JButton();
        jButton_Repostaje = new javax.swing.JButton();
        jButton_Repartidor = new javax.swing.JButton();
        jButton_Pedido = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton_Pizza_Ingrediente = new javax.swing.JButton();
        jButton_Bocadillo_Ingrediente = new javax.swing.JButton();
        jButton_Venta_Articulo = new javax.swing.JButton();
        jButton_ProductoEstrella_Ingrediente = new javax.swing.JButton();
        jButton_Venta_Pedido = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pizzeria Cargo");
        jPanel2.add(jLabel1);

        jLabel2.setText("Tablas Referenciales");

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jButton_TamanhoPizza.setText("Tamaños Pizza");
        jButton_TamanhoPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TamanhoPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TamanhoPizza);

        jButton_TamanhoBocadillo.setText("Tamaños Bocadillo");
        jButton_TamanhoBocadillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TamanhoBocadilloActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TamanhoBocadillo);

        jButton_Articulo.setText("Artículos");
        jButton_Articulo.setToolTipText("");
        jButton_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ArticuloActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Articulo);

        jButton_Ingrediente.setText("Ingredientes");
        jButton_Ingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IngredienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Ingrediente);

        jButton_Venta.setText("Ventas");
        jButton_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VentaActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Venta);

        jButton_Scooter.setText("Scooters");
        jButton_Scooter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScooterActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Scooter);

        jButton_TipoPedido.setText("Tipos Pedido");
        jButton_TipoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TipoPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_TipoPedido);

        jButton_Cliente.setText("Clientes");
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Cliente);

        jLabel3.setText("Tablas de Datos");

        jPanel4.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jButton_Pizza.setText("Pizzas");
        jButton_Pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PizzaActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Pizza);

        jButton_Bocadillo.setText("Bocadillos");
        jButton_Bocadillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BocadilloActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Bocadillo);

        jButton_ProductoEstrella.setText("Productos Estrella");
        jButton_ProductoEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProductoEstrellaActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_ProductoEstrella);

        jButton_Repostaje.setText("Repostajes");
        jButton_Repostaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RepostajeActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Repostaje);

        jButton_Repartidor.setText("Repartidores");
        jButton_Repartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RepartidorActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Repartidor);

        jButton_Pedido.setText("Pedidos");
        jButton_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PedidoActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_Pedido);

        jLabel4.setText("Tablas Interrelacionales");

        jPanel5.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jButton_Pizza_Ingrediente.setText("Pizza - Ingrediente");
        jButton_Pizza_Ingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pizza_IngredienteActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Pizza_Ingrediente);

        jButton_Bocadillo_Ingrediente.setText("Bocadillo - Ingrediente");
        jButton_Bocadillo_Ingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Bocadillo_IngredienteActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Bocadillo_Ingrediente);

        jButton_Venta_Articulo.setText("Venta - Artículo");
        jButton_Venta_Articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Venta_ArticuloActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Venta_Articulo);

        jButton_ProductoEstrella_Ingrediente.setText("Producto Estrella - Ingrediente");
        jButton_ProductoEstrella_Ingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProductoEstrella_IngredienteActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_ProductoEstrella_Ingrediente);

        jButton_Venta_Pedido.setText("Venta - Pedido");
        jButton_Venta_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Venta_PedidoActionPerformed(evt);
            }
        });
        jPanel5.add(jButton_Venta_Pedido);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(6, 6, 6))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TamanhoPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TamanhoPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TamanhoPizzaActionPerformed

    private void jButton_TamanhoBocadilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TamanhoBocadilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TamanhoBocadilloActionPerformed

    private void jButton_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ArticuloActionPerformed

    private void jButton_IngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_IngredienteActionPerformed

    private void jButton_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_VentaActionPerformed

    private void jButton_ScooterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScooterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ScooterActionPerformed

    private void jButton_TipoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TipoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TipoPedidoActionPerformed

    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jButton_PizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PizzaActionPerformed

    private void jButton_BocadilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BocadilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BocadilloActionPerformed

    private void jButton_ProductoEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProductoEstrellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ProductoEstrellaActionPerformed

    private void jButton_RepostajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RepostajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RepostajeActionPerformed

    private void jButton_RepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RepartidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RepartidorActionPerformed

    private void jButton_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PedidoActionPerformed

    private void jButton_Pizza_IngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pizza_IngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Pizza_IngredienteActionPerformed

    private void jButton_Bocadillo_IngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Bocadillo_IngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Bocadillo_IngredienteActionPerformed

    private void jButton_Venta_ArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Venta_ArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Venta_ArticuloActionPerformed

    private void jButton_ProductoEstrella_IngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProductoEstrella_IngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ProductoEstrella_IngredienteActionPerformed

    private void jButton_Venta_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Venta_PedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Venta_PedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzeriaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzeriaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzeriaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzeriaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzeriaCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Articulo;
    private javax.swing.JButton jButton_Bocadillo;
    private javax.swing.JButton jButton_Bocadillo_Ingrediente;
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_Ingrediente;
    private javax.swing.JButton jButton_Pedido;
    private javax.swing.JButton jButton_Pizza;
    private javax.swing.JButton jButton_Pizza_Ingrediente;
    private javax.swing.JButton jButton_ProductoEstrella;
    private javax.swing.JButton jButton_ProductoEstrella_Ingrediente;
    private javax.swing.JButton jButton_Repartidor;
    private javax.swing.JButton jButton_Repostaje;
    private javax.swing.JButton jButton_Scooter;
    private javax.swing.JButton jButton_TamanhoBocadillo;
    private javax.swing.JButton jButton_TamanhoPizza;
    private javax.swing.JButton jButton_TipoPedido;
    private javax.swing.JButton jButton_Venta;
    private javax.swing.JButton jButton_Venta_Articulo;
    private javax.swing.JButton jButton_Venta_Pedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
